var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return $jscomp.arrayIterator(a);throw Error(String(a)+" is not an iterable or ArrayLike");};
$jscomp.arrayFromIterator=function(a){for(var b,e=[];!(b=a.next()).done;)e.push(b.value);return e};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
var info="",url=window.location.href,con=$("#pagebody").prop("outerHTML"),jsonData=JSON.parse($("#item-page-app-data").html()),style={width:"auto",padding:"20px",background:"#ffffff",position:"fixed",top:"70px",left:"10px","font-size":"12px","letter-spacing":"0.05em","line-height":"1.7","text-align":"left",border:"2px solid #cccccc","z-index":"9999999999"},iFlag=con.indexOf('id="info"');-1!==iFlag&&$("#info").remove();
var spl=url.split("/"),numSet=spl[spl.length-2],br1=numSet.slice(0,1),br4=numSet.slice(0,4),uFlag=con.indexOf("\u3053\u306e\u5546\u54c1\u306f\u58f2\u308a\u5207\u308c\u3067\u3059");-1!==uFlag&&(info+='<span style="color:#dd0000;">\u58f2\u308a\u5207\u308c</span><br><br>');var bFlag=con.indexOf("\u30d6\u30e9\u30f3\u30c9\u516c\u5f0f\u30b5\u30a4\u30c8\u63b2\u8f09\u4fa1\u683c");if(-1!==bFlag)var bPrice=$(".pr_cp_p").text().replace("\u5186",""),bPriceNum=Number(bPrice.replace(",",""));
var tblinfo="",prices=[],referencePrices=[],discountRates=[],minPrice=0,maxReference=0,maxReferencePrefix="",maxRate=0,minFlag="",maxFlag="",maxRateFlag="",discountRate="";
jsonData.api.data.itemInfoSku.sku.forEach(function(a){var b=a.variantId,e=a.selectorValues.join(" : "),h=Intl.NumberFormat("ja-JP").format(Math.floor(a.taxIncludedPrice))+"\u5186",g=a.taxIncludedReferencePrice?Intl.NumberFormat("ja-JP").format(Math.floor(a.taxIncludedReferencePrice))+"\u5186":"\uff0d",c=Math.floor(a.taxIncludedPrice);prices.includes(c)||prices.push(c);a.taxIncludedReferencePrice&&(c=Math.floor(a.taxIncludedReferencePrice),referencePrices.includes(c)||referencePrices.push(c));c=a.referencePricePrefix||
"";var f="";if(""!==c&&bPriceNum)c="\u30d6\u30e9\u30f3\u30c9\u516c\u5f0f\u30b5\u30a4\u30c8\u63b2\u8f09\u4fa1\u683c",f="\u3010\u30d6\u3011",g=bPriceNum;else switch(c){case "\u5f53\u5e97\u901a\u5e38\u4fa1\u683c":f="\u3010\u5f53\u3011";break;case "\u30e1\u30fc\u30ab\u30fc\u5e0c\u671b\u5c0f\u58f2\u4fa1\u683c":f="\u3010\u30e1\u3011"}var d=a.taxIncludedReferencePrice?Math.round(100*(1-a.taxIncludedPrice/a.taxIncludedReferencePrice)):"\uff0d";"\uff0d"===d||discountRates.includes(d)?"\uff0d"!==d||discountRates.includes(0)||
discountRates.push(0):discountRates.push(d);maxReference<Math.floor(a.taxIncludedReferencePrice)&&(maxReference=Math.floor(a.taxIncludedReferencePrice),maxReferencePrefix=c);tblinfo+='<tr><th style="vertical-align: middle;">'+b+"</th><td>"+e+"</td><td>"+h+"</td><td>"+f+g+"</td><td>"+("\uff0d"===d?"\uff0d":d+"%")+"</td></tr>"});1<prices.length?(minPrice=Math.min.apply(Math,$jscomp.arrayFromIterable(prices)),minFlag="\u3010\u6700\u5c0f\u3011"):1===prices.length&&(minPrice=prices[0],minFlag="");
1<referencePrices.length?(maxReference=Math.max.apply(Math,$jscomp.arrayFromIterable(referencePrices)),maxFlag="\u3010\u6700\u5927\u3011"):1===referencePrices.length&&(maxReference=referencePrices[0],maxFlag="");1<discountRates.length?(maxRate=Math.max.apply(Math,$jscomp.arrayFromIterable(discountRates)),maxRateFlag="\u3010\u6700\u5927\u3011"):1===discountRates.length&&(maxRate=discountRates[0],maxRateFlag="");
info=info+"\u8ca9\u58f2\u4fa1\u683c\uff1a"+Intl.NumberFormat("ja-JP").format(minPrice)+"\u5186"+minFlag;0<maxReference&&(info=info+"<br>"+maxReferencePrefix+" "+Intl.NumberFormat("ja-JP").format(maxReference)+"\u5186"+maxFlag,info=info+"<br>\u5272\u5f15\u7387 "+(0===maxRate?"\uff0d":maxRate+"%")+maxRateFlag);var kFlag=con.indexOf("timeSalePeriod");if(-1!==kFlag){var kPeriod=$(".normal_reserve_time_sale:not(#timeSalePeriod)").text();info=info+"<br>\u8ca9\u58f2\u671f\u9593 "+kPeriod}
nmlPoint=Math.floor(Math.round(minPrice/1.1)/100);info=info+"<br><br>\u30dd\u30a4\u30f3\u30c8 1\u500d\uff08"+nmlPoint+" pt\uff09";var pFlag=con.indexOf('class="multiplier');if(-1!==pFlag){var camp=$(".multiplier + li").text().replace("\u500dUP",""),cX=Number(camp)+1,cPoint=nmlPoint*cX;info=info+"<br>\u30dd\u30a4\u30f3\u30c8 "+cX+"\u500d\uff08"+cPoint+" pt\uff09"}var img01=$("#itemImg").find('img[src*="'+numSet+'"]').attr("src"),img02=$("#pagebody").find('img[src^="https://tshop.r10s.jp/"]').attr("src");
info=info+'<br><br><img src="'+img01+'" width="100">\u3000<img src="'+img02+'" width="100">';info=info+'<br><br><div style="max-height: 300px; overflow:auto;"><table style="width:100%; font-size: 10px; border-collapse:separate; border-spacing: 15px 5px; background:#eee;">'+tblinfo+"</table></div>";var folderA="\\\\128.1.100.13\\\u901a\u8ca9\\ItemImage\\up\u6e08\\"+br1+"\\"+br4+"\\"+numSet;info=info+'<br><input type="text" value="'+folderA+'" onclick="this.select();" style="width:250px; height:30px;">';
var zUrl="https://item.rms.rakuten.co.jp/rms-item/shops/192229/item/edit/"+numSet,jsUrl="'"+zUrl+"','subwin','width=1200,height=800,top=30,left=500'";info=info+'\u3000<button type="button"href="javascript:void(0);" onclick="window.open('+jsUrl+')" style="margin-top:5px; padding:3px;">\u3000\u5225\u7a93RMS\u3000</button>';$("#pagebody").prepend('<div id="info">'+info+"</div>");$("#info").css(style);window.location.hash="";window.location.hash="rakutenLimitedId_aroundCart";
var x=window.pageXOffset,y=window.pageYOffset;window.scrollTo(x,y-150);